app.controller('postsController', function($scope, $routeParams){

	$scope.rowCollection = [
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0},
			{title:"Why do we need new IITs?", author:"Ranveer Aggarwal", when:"14th December 2015", content: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.", tags:["IIT Bombay", "New IITs"], upvotes: 5, downvotes:0}
	];
});
